accueil:
    path: /
    controller: App\Controller\AccueilController::index
ajouter_anime:
    path: /ajouter-anime
    controller: App\Controller\AnimeController::ajouterAnime
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
